// <auto-generated />
using MarianelaVeras_Ap1_P1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarianelaVeras_Ap1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241008174535_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MarianelaVeras_Ap1_P1.Models.Deudores", b =>
                {
                    b.Property<int>("DeudorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeudorId");

                    b.ToTable("Deudores");

                    b.HasData(
                        new
                        {
                            DeudorId = 1,
                            Nombres = "Unohana Retsu"
                        },
                        new
                        {
                            DeudorId = 2,
                            Nombres = "Kurosaki Ichigo"
                        },
                        new
                        {
                            DeudorId = 3,
                            Nombres = "Zaraki Kenpachii"
                        },
                        new
                        {
                            DeudorId = 4,
                            Nombres = "Roronoa Zoro"
                        },
                        new
                        {
                            DeudorId = 5,
                            Nombres = "Monkey D. Luffy"
                        },
                        new
                        {
                            DeudorId = 6,
                            Nombres = "Soul King Brook"
                        },
                        new
                        {
                            DeudorId = 7,
                            Nombres = "Uzumaki Naruto"
                        },
                        new
                        {
                            DeudorId = 8,
                            Nombres = "Uchiha Sasuke"
                        },
                        new
                        {
                            DeudorId = 9,
                            Nombres = "Hatake Kakashi"
                        },
                        new
                        {
                            DeudorId = 10,
                            Nombres = "Haruno Sakura"
                        });
                });

            modelBuilder.Entity("MarianelaVeras_Ap1_P1.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("PrestamoId");

                    b.HasIndex("DeudorId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("MarianelaVeras_Ap1_P1.Models.Prestamos", b =>
                {
                    b.HasOne("MarianelaVeras_Ap1_P1.Models.Deudores", "Deudor")
                        .WithMany()
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });
#pragma warning restore 612, 618
        }
    }
}
